export const Users = [
  {
    id:11,
    profilePicture: "assets/person/11.jpg",
    username: "Aditya Roy Kapoor",
  },
  {
    id:12,
    profilePicture: "assets/person/12.jpg",
    username: "Anu Emmanuel",
  },
  {
    id:17,
    profilePicture: "assets/person/17.jpg",
    username: "Safras",
  },
  {
    id:13,
    profilePicture: "assets/person/13.jpg",
    username: "Rashmika Mandanna",
  },
  {
    id:14,
    profilePicture: "assets/person/14.jpg",
    username: "Pooja Hegde",
  },
  {
    id:15,
    profilePicture: "assets/person/15.jpg",
    username: "Cristiano Ronaldo",
  },
  {
    id:16,
    profilePicture: "assets/person/16.jpg",
    username: "Samyuktha Menon",
  },
  {
    id:18,
    profilePicture: "assets/person/18.jpg",
    username: "David Beckham",
  },

  {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    // {
    //   id: 15,
    //   desc: "Work Hard !",
    //   photo: "assets/post/15.jpg",
    //   date: "5 mins ago",
    //   userId: 15,
    //   like: 332,
    //   comment: 96,
    // },
    {
      id: 15,
      desc: "Work Hard ! Let your Success Shine",
      photo: "assets/post/15.jpg",
      date: "5 mins ago",
      userId: 15,
      like: 32,
      comment: 9,
    },
    {
      id: 12,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/12.jpg",
      date: "5 mins ago",
      userId: 12,
      like: 30,
      comment: 19,
    },
    {
      id: 16,
      photo: "assets/post/16.jpg",
      date: "15 mins ago",
      userId: 16,
      like: 2,
      comment: 1,
    },
    {
      id: 11,
      photo: "assets/post/11.jpg",
      date: "15 mins ago",
      userId: 11,
      like: 21,
      comment: 41,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 14,
      photo: "assets/post/14.jpg",
      date: "4 hours ago",
      userId: 14,
      like: 47,
      comment: 13,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 17,
      photo: "assets/post/17.jpg",
      date: "5 hours ago",
      userId: 17,
      like: 213,
      comment: 51,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 18,
      photo: "assets/post/18.jpg",
      date: "1 day ago",
      userId: 18,
      like: 144,
      comment: 61,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 13,
      desc: "Change the world by being yourself.",
      photo: "assets/post/13.jpg",
      date: "5 days ago",
      userId: 13,
      like: 112,
      comment: 22,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  